version: '3'

tasks:
  default:
    deps:
      - run-frontend
      - run-backend

  run-frontend:
    desc: Run the next.js dev server 
    deps:
      - setup-frontend
    dir: frontend
    dotenv:
      - ./frontend/.env
    cmds:
      - npm run dev

  run-backend:
    desc: Run the backend go server
    dir: server
    deps:
      - oapi
    cmds:
      - go run main.go

  setup-frontend:
    desc: Install the frontend dependencies
    dir: frontend
    cmds:
      - npm install

  oapi:
    desc: Generate the OpenAPI spec
    dir: server
    cmds:
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.4.1 -package oapi -generate chi-server,types,strict-server -o ./oapi/api.gen.go ./oapi/openapi.yaml 
